// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQD6S7VOFtPRIR_v7C9qRcq0QjzXDlpTQ',
    appId: '1:284980732824:web:3365d470c9a5ba807781ed',
    messagingSenderId: '284980732824',
    projectId: 'esp32-test-a1771',
    authDomain: 'esp32-test-a1771.firebaseapp.com',
    databaseURL: 'https://esp32-test-a1771-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-test-a1771.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChHbQEE3oHf5E_tNZmDRlppzr6jaYGfio',
    appId: '1:284980732824:android:5c28fa08968aaff47781ed',
    messagingSenderId: '284980732824',
    projectId: 'esp32-test-a1771',
    databaseURL: 'https://esp32-test-a1771-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-test-a1771.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1k1xDxYBXQCHJsfrfAz5XWTZlKfECo2g',
    appId: '1:284980732824:ios:606bd71197aa080d7781ed',
    messagingSenderId: '284980732824',
    projectId: 'esp32-test-a1771',
    databaseURL: 'https://esp32-test-a1771-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-test-a1771.firebasestorage.app',
    iosBundleId: 'com.example.smartBackpack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1k1xDxYBXQCHJsfrfAz5XWTZlKfECo2g',
    appId: '1:284980732824:ios:606bd71197aa080d7781ed',
    messagingSenderId: '284980732824',
    projectId: 'esp32-test-a1771',
    databaseURL: 'https://esp32-test-a1771-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-test-a1771.firebasestorage.app',
    iosBundleId: 'com.example.smartBackpack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQD6S7VOFtPRIR_v7C9qRcq0QjzXDlpTQ',
    appId: '1:284980732824:web:3ccd70d36bdbb5617781ed',
    messagingSenderId: '284980732824',
    projectId: 'esp32-test-a1771',
    authDomain: 'esp32-test-a1771.firebaseapp.com',
    databaseURL: 'https://esp32-test-a1771-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-test-a1771.firebasestorage.app',
  );
}
